src/main/resources/templates/board/readingCounsel.html

댓글 수정, 삭제 이미지 a태그 삭제

---

src/main/resources/templates/admin/memberShipMm.html
src/main/resources/templates/counselor/book/counselorBook.html
src/main/resources/templates/counselor/free/freeRegistration.html
src/main/resources/templates/counselor/pay/Registration.html
src/main/resources/templates/main/map.html
src/main/resources/templates/test/anxiety.html
src/main/resources/templates/test/bipolarDisorder.html
src/main/resources/templates/test/diagnosis.html
src/main/resources/templates/test/stress.html
src/main/resources/templates/user/changePw.html
src/main/resources/templates/user/findId.html
src/main/resources/templates/user/findPw.html

헤더 푸터 작업끝 - 의진

---

src/main/java/com/example/redmedicine/controller/UserController.java
src/main/java/com/example/redmedicine/mapper/UserMapper.java
src/main/java/com/example/redmedicine/service/UserService.java
src/main/resources/templates/counselor/book/bookingDetails.html
src/main/resources/templates/counselor/book/bookingDetails02.html
src/main/resources/templates/counselor/book/bookingDetails03.html
src/main/resources/templates/counselor/book/myCounselor.html
src/main/resources/templates/counselor/free/councelorProfileFree.html
src/main/resources/templates/counselor/pay/councelorProfilePay.html
src/main/resources/templates/counselor/pay/payment.html
src/main/resources/templates/main/privacy.html
src/main/resources/templates/main/terms.html
src/main/resources/templates/user/login.html
src/main/resources/templates/user/myDaybook.html
src/test/java/com/example/redmedicine/service/UserServiceTest.java

login.html 일부 수정 및
userController 일부 추가

제가 담당했던 페이지들 헤더와 풋터 수정,

---

src/main/resources/templates/board/counselBoard.html

상담게시판 헤더,푸터 fragment작업 -지윤

---

src/main/resources/templates/board/counselBoard.html
src/main/resources/templates/board/diary.html
src/main/resources/templates/board/notice.html
src/main/resources/templates/board/readingCounsel.html
src/main/resources/templates/board/readingDiary.html
src/main/resources/templates/board/readingNotice.html
src/main/resources/templates/board/writingCounsel.html
src/main/resources/templates/board/writingDiary.html
src/main/resources/templates/board/writingNotice.html
src/main/resources/templates/fragments/afterLoginHeader.html

담당 퍼블리싱 페이지 fragment 작업, css경로 수정

담당 퍼블리싱 페이지 fragment 작업, css경로 수정 -지윤

---

src/main/java/com/example/redmedicine/controller/BoardController.java
src/main/java/com/example/redmedicine/controller/CounselorController.java
src/main/java/com/example/redmedicine/controller/TestController.java
src/main/java/com/example/redmedicine/controller/UserController.java
src/main/resources/templates/test/anxiety.html
src/main/resources/templates/test/bipolarDisorder.html
src/main/resources/templates/test/diagnosis.html
src/main/resources/templates/test/stress.html

boardController, CounselorController, TestController 추가, 담당 페이지 경로 -지윤

boardController, CounselorController, TestController 추가, 담당 페이지 경로 -지윤

---

src/main/java/com/example/redmedicine/controller/AdmianController.java
src/main/java/com/example/redmedicine/mapper/AdminMapper.java
src/main/java/com/example/redmedicine/service/AdminService.java
src/main/resources/config/config.xml
src/main/resources/mapper/AdminMapper.xml
src/main/resources/static/css/admin/memberShipMm.css
src/main/resources/templates/admin/memberShipMm.html

유대훈 회원정보관리 데이터 적용

---

src/main/java/com/example/redmedicine/controller/DiaryController.java
src/main/java/com/example/redmedicine/controller/NoticeController.java
src/main/java/com/example/redmedicine/domain/dto/NoticeDto.java
src/main/java/com/example/redmedicine/domain/vo/NoticeVo.java
src/main/java/com/example/redmedicine/mapper/NoticeMapper.java
src/main/java/com/example/redmedicine/service/NoticeService.java
src/main/resources/config/config.xml
src/main/resources/mapper/NoticeMapper.xml
src/main/resources/static/css/board/readingNotice.css
src/main/resources/templates/board/diary.html
src/main/resources/templates/board/notice.html
src/main/resources/templates/board/readingNotice.html
src/main/resources/templates/board/writingDiary.html
src/main/resources/templates/board/writingNotice.html

-공지사항 페이지 글 작성 시 db에 데이터 들어가도록 처리
-공지사항 페이지 글 작성 후 방금 작성한 글 상세페이지로 이동, 글 정보 불러오기

공지사항 페이지 글작성, 상세페이지-지윤

---

src/main/java/com/example/redmedicine/controller/UserController.java
src/main/java/com/example/redmedicine/mapper/UserMapper.java
src/main/java/com/example/redmedicine/service/UserService.java
src/main/resources/config/config.xml
src/main/resources/mapper/UserMapper.xml
src/main/resources/static/js/counselor/free/counselorProfileFree.js
src/main/resources/static/js/user/mypage.js
src/main/resources/templates/user/mypage.html

UserMapper, 인터페이스,
UserService,UserController,
config,mypage등 수정

회원 정보 수정 페이지까지 진입 했으나 아직 수정이 불가능 - 동현

---

src/main/java/com/example/redmedicine/controller/AdmianController.java
src/main/java/com/example/redmedicine/domain/vo/Criteria.java
src/main/java/com/example/redmedicine/domain/vo/PageVo.java
src/main/java/com/example/redmedicine/mapper/AdminMapper.java
src/main/java/com/example/redmedicine/service/AdminService.java
src/main/resources/config/config.xml
src/main/resources/mapper/AdminMapper.xml
src/main/resources/static/css/admin/memberShipMm.css
src/main/resources/templates/admin/memberShipMm.html

config 수정 -> pageVo 추가
pageVo 생성
팀장님 config 확인해주세요!

유대훈 회원정보관리 폼 수정 완료  /  페이징 작업중

---

src/main/java/com/example/redmedicine/controller/NoticeController.java
src/main/java/com/example/redmedicine/domain/vo/PageVo.java
src/main/java/com/example/redmedicine/mapper/NoticeMapper.java
src/main/java/com/example/redmedicine/service/NoticeService.java
src/main/resources/config/config.xml
src/main/resources/mapper/NoticeMapper.xml
src/main/resources/static/css/board/notice.css
src/main/resources/static/css/board/readingNotice.css
src/main/resources/static/js/board/readingNotice.js
src/main/resources/templates/board/modifyNotice.html
src/main/resources/templates/board/notice.html
src/main/resources/templates/board/readingNotice.html

*공지사항 리스트 불러오기
-한 페이지 당 글 10개씩 불러오기
*공지사항 리스트 페이징처리
-페이지 번호 클릭 시 해당 페이지로 이동, 다음/이전 버튼 클릭 시 다음/이전 세트로 이동
*공지사항 글 제목 클릭 시 해당 글 상세 페이지로 이동 처리
*수정 ,삭제 
-수정 버튼 클릭 시 수정페이지로 이동/ 해당 글의 정보 화면에 뿌림(제목,내용)
-삭제 버튼 클릭 시 "글을 삭제하시겠습니까?" 확인창 띄우고 확인버튼 클릭 시 해당 글 목록과 DB에서 삭제처리

공지사항 페이지 작업중 (90%)-지윤

---

src/main/java/com/example/redmedicine/controller/CounselorBoardController.java
src/main/java/com/example/redmedicine/controller/UserController.java
src/main/java/com/example/redmedicine/domain/dto/CounselorDto.java
src/main/java/com/example/redmedicine/domain/vo/CounselorVo.java
src/main/java/com/example/redmedicine/mapper/CounselorMapper.java
src/main/java/com/example/redmedicine/service/CounselorService.java
src/main/resources/mapper/CounselorMapper.xml
src/main/resources/templates/board/counselBoard.html
src/main/resources/templates/board/readingCounsel.html
src/main/resources/templates/board/writingCounsel.html
src/main/resources/templates/fragments/header.html

상담 게시판 페이징 처리중
userLevel처리 확인 중

상담게시판 글보기 글쓰기 완료 - 동현

---

src/main/java/com/example/redmedicine/controller/DiaryController.java
src/main/java/com/example/redmedicine/controller/NoticeController.java
src/main/java/com/example/redmedicine/domain/dto/DiaryDto.java
src/main/java/com/example/redmedicine/domain/dto/NoticeDto.java
src/main/java/com/example/redmedicine/domain/vo/DiaryVo.java
src/main/java/com/example/redmedicine/mapper/DiaryMapper.java
src/main/java/com/example/redmedicine/service/DiaryService.java
src/main/resources/config/config.xml
src/main/resources/mapper/DiaryMapper.xml
src/main/resources/static/css/board/diary.css
src/main/resources/static/css/board/notice.css
src/main/resources/static/css/board/readingDiary.css
src/main/resources/static/js/board/diary.js
src/main/resources/static/js/board/notice.js
src/main/resources/templates/board/diary.html
src/main/resources/templates/board/modifyDiary.html
src/main/resources/templates/board/notice.html
src/main/resources/templates/board/readingDiary.html
src/main/resources/templates/board/writingNotice.html

일기쓰기 페이지 - 90%완료
-리스트 불러오기
-페이징처리 
-글 제목 클릭 시 해당 상세 페이지로 이동 
-수정 ,삭제 
>수정 버튼 클릭 시 수정페이지로 이동/ 해당 글의 정보 화면에 뿌림(제목,내용)
>삭제 버튼 클릭 시 "글을 삭제하시겠습니까?" 확인창 띄우고 확인버튼 클릭 시 해당 글 목록과 DB에서 삭제처리
-헤더에서 커뮤니티 클릭 시 공지사항 리스트 페이지로 이동하도록 처리

일기쓰기 페이지 - 90%완료/지윤

---

src/main/java/com/example/redmedicine/controller/CounselorBoardController.java
src/main/resources/mapper/CounselorMapper.xml
src/main/resources/static/css/board/counselBoard.css
src/main/resources/static/css/board/readingCounsel.css
src/main/resources/static/css/board/writingCounsel.css
src/main/resources/static/css/main/map.css
src/main/resources/static/css/user/join.css
src/main/resources/static/css/user/login.css
src/main/resources/static/css/user/mypage.css
src/main/resources/static/js/board/readingCounsel.js
src/main/resources/templates/board/modifyCounsel.html
src/main/resources/templates/board/readingCounsel.html

상담 게시판 CRUD 완료했습니다. - 동현

---

src/main/java/com/example/redmedicine/controller/CFileController.java
src/main/java/com/example/redmedicine/controller/CounselorBoardController.java
src/main/java/com/example/redmedicine/mapper/CFileMapper.java
src/main/java/com/example/redmedicine/service/CFileService.java
src/main/java/com/example/redmedicine/service/CounselorService.java
src/main/resources/mapper/CFileMapper.xml
src/main/resources/static/css/board/counselBoard.css
src/main/resources/static/css/board/readingCounsel.css
src/main/resources/static/css/board/writingCounsel.css
src/main/resources/static/css/main/map.css
src/main/resources/static/css/user/join.css
src/main/resources/static/css/user/login.css
src/main/resources/static/css/user/mypage.css
src/main/resources/static/js/board/readingCounsel.js
src/main/resources/templates/board/counselBoard.html
src/main/resources/templates/board/readingCounsel.html
src/main/resources/templates/board/writingCounsel.html

상담 게시판 첨부파일의 이미지를 readingCounsel에서 읽어오지 못하는 오류 수정 중!

상담 게시판 첨부파일 수정 중 - 동현

---

src/main/resources/static/css/board/notice.css
src/main/resources/static/css/board/readingDiary.css
src/main/resources/static/css/board/readingNotice.css
src/main/resources/static/css/board/writingDiary.css
src/main/resources/static/css/board/writingNotice.css
src/main/resources/static/css/counselor/pay/payment.css
src/main/resources/static/css/test/anxiety.css
src/main/resources/static/css/test/bipolarDisorder.css
src/main/resources/static/css/test/diagnosis.css
src/main/resources/static/css/test/stress.css
src/main/resources/static/css/user/changePw.css
src/main/resources/static/css/user/findId.css
src/main/resources/static/css/user/findPw.css
src/main/resources/templates/board/diary.html
src/main/resources/templates/board/modifyDiary.html
src/main/resources/templates/board/modifyNotice.html
src/main/resources/templates/board/notice.html
src/main/resources/templates/board/readingDiary.html
src/main/resources/templates/board/readingNotice.html
src/main/resources/templates/board/writingDiary.html
src/main/resources/templates/board/writingNotice.html
src/main/resources/templates/test/anxiety.html
src/main/resources/templates/test/bipolarDisorder.html
src/main/resources/templates/test/diagnosis.html
src/main/resources/templates/test/stress.html
src/main/resources/templates/user/findPw.html

-담당 페이지 : 페이지 이동처리, 헤더 css 변경 /지윤

-담당 페이지 : 페이지 이동처리, 헤더 css 변경 /지윤

---

build.gradle
src/main/java/com/example/redmedicine/controller/SmsRestController.java
src/main/java/com/example/redmedicine/controller/UserController.java
src/main/java/com/example/redmedicine/controller/UserRestController.java
src/main/java/com/example/redmedicine/mapper/UserMapper.java
src/main/java/com/example/redmedicine/service/SmsService.java
src/main/java/com/example/redmedicine/service/UserService.java
src/main/resources/mapper/UserMapper.xml
src/main/resources/static/css/board/diary.css
src/main/resources/static/css/board/notice.css
src/main/resources/static/css/board/readingDiary.css
src/main/resources/static/css/board/readingNotice.css
src/main/resources/static/css/board/writingDiary.css
src/main/resources/static/css/board/writingNotice.css
src/main/resources/static/css/counselor/pay/payment.css
src/main/resources/static/css/test/anxiety.css
src/main/resources/static/css/test/bipolarDisorder.css
src/main/resources/static/css/test/diagnosis.css
src/main/resources/static/css/test/stress.css
src/main/resources/static/css/user/changePw.css
src/main/resources/static/css/user/findId.css
src/main/resources/static/css/user/findPw.css
src/main/resources/static/js/user/changePw.js
src/main/resources/static/js/user/findPw.js
src/main/resources/templates/user/changePw.html
src/main/resources/templates/user/findPw.html

*담당페이지 헤더 코드 mylist - height : 130px로 변경
*비밀번호 찾기 (100% 완료)
-이름, 휴대폰 번호 입력 후 인증번호 전송 버튼 클릭 시
입력한 휴대폰 번호로 6자리 인증번호 발송
-인증번호 입력 후 확인 클릭 시
입력 정보에 따라 일치하는 회원 유무/인증번호 올바르게 입력했는지 결과 div 띄우기
-일치하는 회원정보가 있고 인증번호를 올바르게 입력했을 경우 확인버튼 나타남
-확인 버튼 클릭 시 비밀번호 변경 페이지로 이동
*비밀번호 변경 (90% 완료 : ※유효성 검사 추가해야함)
-새로운 비밀번호, 비밀번호 확인칸 모두 입력 시 모두 일치하는지 여부를 아래의 div에 보여줌 -비밀번호 변경하기 버튼 클릭 시 "비밀번호를 변경하시겠습니까?"확인창 나타남
-확인 클릭 시 "비밀번호를 변경했습니다." 창 나타나고 로그인 페이지로 이동

비밀번호찾기,비밀번호변경 진행중 -지윤

---

src/main/resources/static/js/user/changePw.js

유효성검사 진행중-지윤

---

src/main/java/com/example/redmedicine/controller/CCommentController.java
src/main/java/com/example/redmedicine/controller/UserController.java
src/main/resources/mapper/CCommentMapper.xml
src/main/resources/static/css/board/counselBoard.css
src/main/resources/static/css/board/readingCounsel.css
src/main/resources/static/css/board/writingCounsel.css
src/main/resources/static/css/main/map.css
src/main/resources/static/css/user/join.css
src/main/resources/static/css/user/login.css
src/main/resources/static/css/user/mypage.css
src/main/resources/static/js/board/readingCounsel.js
src/main/resources/static/js/module/cReply.js
src/main/resources/templates/board/readingCounsel.html
src/main/resources/templates/user/join.html
src/main/resources/templates/user/mypage.html

헤더부분 css 수정 완료
회원 정보 수정 관련 일부 수정

상담 게시판 댓글 기능 수정 중 - 동현

---

src/main/java/com/example/redmedicine/controller/UserRestController.java
src/main/java/com/example/redmedicine/mapper/UserMapper.java
src/main/java/com/example/redmedicine/service/UserService.java
src/main/resources/mapper/UserMapper.xml
src/main/resources/static/css/user/join.css
src/main/resources/static/js/user/join.js
src/main/resources/templates/board/readingCounsel.html
src/main/resources/templates/user/join.html

아직 휴대전화로 인증하는 기능 필요함 - 추후 진행요망
상담 게시판 댓글기능 수정 중

회원가입 유효성 검사 완료 - 동현

---

src/main/java/com/example/redmedicine/controller/CCommentController.java
src/main/java/com/example/redmedicine/service/CCommentService.java
src/main/resources/static/js/board/readingCounsel.js
src/main/resources/static/js/module/cReply.js
src/main/resources/templates/board/readingCounsel.html

상담 게시판 댓글 기능 일부 수정 완료 - 동현

---

src/main/java/com/example/redmedicine/controller/DiaryController.java
src/main/java/com/example/redmedicine/domain/vo/Criteria.java
src/main/java/com/example/redmedicine/service/SmsService.java
src/main/resources/static/css/user/findPw.css
src/main/resources/static/js/board/diary.js
src/main/resources/static/js/board/writingDiary.js
src/main/resources/templates/board/diary.html
src/main/resources/templates/board/readingDiary.html
src/main/resources/templates/board/writingDiary.html

-비밀번호 찾기 페이지 css수정
-일기쓰기 : 글쓰기 페이지에서 제목, 내용, 공개여부 중 하나라도 입력하지 않을 경우 글 등록 불가하도록 처리 
-문자인증 키 application.properties에 추가
-일기쓰기 페이징처리 수정
-일기쓰기 글 읽기 페이지에서 공개여부 숫자표기 -> 공개/비공개 표기 처리

비밀번호찾기 페이지, 일기쓰기 페이지 -지윤

---

src/main/java/com/example/redmedicine/controller/PayController.java
src/main/java/com/example/redmedicine/controller/PayRestController.java
src/main/java/com/example/redmedicine/mapper/PayMapper.java
src/main/java/com/example/redmedicine/mapper/UserMapper.java
src/main/java/com/example/redmedicine/service/PayService.java
src/main/resources/mapper/PayMapper.xml
src/main/resources/mapper/UserMapper.xml
src/main/resources/static/js/counselor/pay/payment.js
src/main/resources/templates/counselor/pay/payment.html
src/main/resources/templates/counselor/pay/registration.html

- 카카오 결제 시 : USER_LEVEL 3으로 변경

결제 페이지 : 카카오결제 완료

---

build.gradle
src/main/java/com/example/redmedicine/controller/BookingController.java
src/main/java/com/example/redmedicine/controller/SmsRestController.java
src/main/java/com/example/redmedicine/domain/dto/BookDto.java
src/main/java/com/example/redmedicine/mapper/BookingMapper.java
src/main/java/com/example/redmedicine/mapper/CounselorMapper.java
src/main/java/com/example/redmedicine/mapper/UserMapper.java
src/main/java/com/example/redmedicine/service/BookingService.java
src/main/java/com/example/redmedicine/service/CounselorService.java
src/main/java/com/example/redmedicine/service/SmsService.java
src/main/java/com/example/redmedicine/service/UserService.java
src/main/resources/mapper/BookingMapper.xml
src/main/resources/mapper/UserMapper.xml
src/main/resources/static/css/counselor/book/bookingContent.css
src/main/resources/static/js/counselor/book/bookingContent.js
src/main/resources/static/js/counselor/book/bookingDetails03.js
src/main/resources/templates/counselor/book/bookingContent.html

상담예약 후 예약 내역 문자 전송 - 지윤

---

src/main/resources/static/css/counselor/book/bookingContent.css
src/main/resources/static/js/counselor/book/bookingContent.js
src/main/resources/static/js/counselor/book/bookingDetails03.js
src/main/resources/templates/counselor/book/bookingContent.html

상담예약 후 메세지 전송-지윤

---

src/main/java/com/example/redmedicine/controller/SmsRestController.java
src/main/java/com/example/redmedicine/domain/dto/CounselorDto.java
src/main/java/com/example/redmedicine/domain/vo/CounselorVo.java
src/main/java/com/example/redmedicine/service/UserService.java
src/main/resources/static/css/board/counselBoard.css
src/main/resources/static/js/user/join.js
src/main/resources/templates/board/counselBoard.html

회원 가입 문자 인증 완료 - 동현

---

src/main/java/com/example/redmedicine/service/SmsService.java
src/main/resources/static/js/counselor/book/bookingContent.js

예약내역 문자전송 기능 수정-지윤

---

src/main/resources/static/css/board/notice.css
src/main/resources/static/css/board/writingDiary.css
src/main/resources/static/css/user/join.css
src/main/resources/templates/board/notice.html
src/main/resources/templates/board/readingNotice.html
src/main/resources/templates/user/join.html

-회원가입페이지 css 수정
-공지사항, 상담게시판 테이블 크기 고정
-일기쓰기 수정, 등록버튼 커서 pointer로 수정
-공지사항 수정, 삭제버튼 / 기능 활성화

담당페이지 세부 작업중-지윤

---

src/main/resources/static/css/user/login.css
src/main/resources/static/css/user/mypage.css

[회원정보수정페이지, 로그인페이지 css 수정 -지윤]

회원정보수정페이지, 로그인페이지 css 수정 -지윤

---

src/main/java/com/example/redmedicine/controller/ProfileController.java
src/main/java/com/example/redmedicine/mapper/ProfileMapper.java
src/main/resources/mapper/ProfileMapper.xml
src/main/resources/static/css/counselor/free/freeMate.css
src/main/resources/static/css/counselor/free/freeRegistration.css
src/main/resources/static/css/counselor/pay/payMate.css
src/main/resources/static/css/counselor/pay/registration.css
src/main/resources/static/css/test/anxiety.css
src/main/resources/static/css/test/bipolarDisorder.css
src/main/resources/static/css/test/diagnosis.css
src/main/resources/static/css/test/stress.css
src/main/resources/static/js/counselor/free/freeRegistration.js
src/main/resources/static/js/counselor/pay/payment.js
src/main/resources/static/js/counselor/pay/registration.js
src/main/resources/templates/counselor/free/counselorProfileFree.html
src/main/resources/templates/counselor/free/freeRegistration.html
src/main/resources/templates/counselor/pay/registration.html
src/main/resources/templates/fragments/header.html
src/main/resources/templates/main/index.html
src/main/resources/templates/test/anxiety.html
src/main/resources/templates/test/bipolarDisorder.html
src/main/resources/templates/test/diagnosis.html
src/main/resources/templates/test/stress.html
src/test/java/com/example/redmedicine/service/ProfileServiceTest.java

무료상담사 프로필 - 삭제 가능하게 처리
상담사 프로필 목록 - 영역을 모두 선택하면 화면이 밀리는 현상 수정
결제 후 - 재로그인 하여서 사용하도록 진행
무료,유료 상담사 등록 - input 모두 체크 하지 않으면 오류페이지로 이동하지
않고 알려주게 수정.
드룹다운 > 상담사신청 , 메인 > 상담사신청 - 상담사신청 글로 바로가기
상담사등록 - 무료 상담사 등록 페이지 접근 권한 userLevel = 2 가 아니면 공지사항으로 페이지 이동, |1명이 1개의 프로필만 등록 할수 있도록 수정.

최종회의내용(전체수정완료) - 의진

---

src/main/java/com/example/redmedicine/controller/UserController.java
src/main/java/com/example/redmedicine/controller/UserRestController.java
src/main/java/com/example/redmedicine/mapper/UserMapper.java
src/main/java/com/example/redmedicine/service/UserService.java
src/main/resources/mapper/UserMapper.xml
src/main/resources/static/css/board/diary.css
src/main/resources/static/css/board/notice.css
src/main/resources/static/css/board/readingDiary.css
src/main/resources/static/css/board/readingNotice.css
src/main/resources/static/css/board/writingDiary.css
src/main/resources/static/css/board/writingNotice.css
src/main/resources/static/css/user/changePw.css
src/main/resources/static/css/user/checkPw.css
src/main/resources/static/css/user/findId.css
src/main/resources/static/css/user/findPw.css
src/main/resources/static/js/user/checkPw.js
src/main/resources/templates/fragments/header.html
src/main/resources/templates/user/checkPw.html

회원정보수정 페이지 진입 시 비밀번호 확인 기능, 담당 페이지 헤더 css 수정  - 지윤

회원정보수정 페이지 진입 시 비밀번호 확인 기능, 담당 페이지 헤더 css 수정  - 지윤
